# ==============================================================================
# IQdesktop docker-compose template file
# ==============================================================================

version: '2.4'
services:
  IQdesktop_%USER%:
    image: %IMAGE%
    hostname: IQdesktop
    shm_size: "%SHM_SIZE_GB%gb"
    privileged: %PRIVILEGED%
    cpus: %NR_CORES%
    mem_limit: "%MEMORY_GB%gb"
    ports:
      - "%VNCPORT%:5901"
      - "%SSHPORT%:22"
      - "%SHINY_SERVER_PORT%:3838"
    environment:
      - ORGANIZATION=%ORGANIZATION%
      - LICENSEKEY=%LICENSEKEY%
      - TIMEZONE=%TIMEZONE%
      - USER=%USER%  
      - PASSWORD=%PASSWORD%
      - ALLOW_SUDO=%ALLOW_SUDO%
      - USER_ID=%USER_ID%
      - HOST_ID=%HOST_ID%
      - HOST_OS=linux # Keep as is ... the multi user environment is for Linux!
      - THEME=%THEME%
      - IQREPORT_LICENSE_KEY=%IQREPORT_LICENSE_KEY%
      - IQRTOOLS_COMPLIANCE=%IQRTOOLS_COMPLIANCE%
      - IQREPORT_TEMPLATE=%IQREPORT_TEMPLATE%
      - NONMEM_LICENSE_KEY=%NONMEM_LICENSE_KEY%
      - MONOLIX_LICENSE_KEY=%MONOLIX_LICENSE_KEY%
      - 'MATLAB_LICENSE_FILE=%MATLAB_LICENSE_FILE%'
      - VNC_PRIVATE_KEY=%VNC_PRIVATE_KEY%
      - VNC_CERTIFICATE=%VNC_CERTIFICATE%
      - SSH_SERVER=%SSH_SERVER%
      - ALLOW_SHINY_SERVER=%ALLOW_SHINY_SERVER%
      - AWS_ACCESS_KEY_ID=%AWS_ACCESS_KEY_ID%
      - AWS_SECRET_ACCESS_KEY=%AWS_SECRET_ACCESS_KEY%
      - MOUNT_BASENAME=%MOUNT_BASENAME%
      - MOUNT_1_LABEL=%MOUNT_1_LABEL%
      - MOUNT_1_SERVER_IP=%MOUNT_1_SERVER_IP%
      - MOUNT_1_SERVER_FOLDER=%MOUNT_1_SERVER_FOLDER%
      - MOUNT_1_OPTIONS=%MOUNT_1_OPTIONS%
      - MOUNT_2_LABEL=%MOUNT_2_LABEL%
      - MOUNT_2_SERVER_IP=%MOUNT_2_SERVER_IP%
      - MOUNT_2_SERVER_FOLDER=%MOUNT_2_SERVER_FOLDER%
      - MOUNT_2_OPTIONS=%MOUNT_2_OPTIONS%
      - MOUNT_3_LABEL=%MOUNT_3_LABEL%
      - MOUNT_3_SERVER_IP=%MOUNT_3_SERVER_IP%
      - MOUNT_3_SERVER_FOLDER=%MOUNT_3_SERVER_FOLDER%
      - MOUNT_3_OPTIONS=%MOUNT_3_OPTIONS%
      - MOUNT_4_LABEL=%MOUNT_4_LABEL%
      - MOUNT_4_SERVER_IP=%MOUNT_4_SERVER_IP%
      - MOUNT_4_SERVER_FOLDER=%MOUNT_4_SERVER_FOLDER%
      - MOUNT_4_OPTIONS=%MOUNT_4_OPTIONS%
      - MOUNT_5_LABEL=%MOUNT_5_LABEL%
      - MOUNT_5_SERVER_IP=%MOUNT_5_SERVER_IP%
      - MOUNT_5_SERVER_FOLDER=%MOUNT_5_SERVER_FOLDER%
      - MOUNT_5_OPTIONS=%MOUNT_5_OPTIONS%
